version: "2"
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5451:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=111
      - ./data:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

